version: '3.4'
networks:
  cloud-consult:
    external: true
services:
  cloudconsult.apigateway:
    networks:
      - cloud-consult
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "6000:80"
      - "6001:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro